apiVersion: v1
kind: ConfigMap
data:
  prometheus.yml: |-
    - module: prometheus
      metricsets: ["remote_write"]
      host: "0.0.0.0"
      port: "9201"
metadata:
  name: prometheus
  namespace: openshift-user-workload-monitoring
