---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metricbeat
  namespace: openshift-user-workload-monitoring
  labels:
    k8s-app: metricbeat
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: metricbeat-user-workloads
  namespace: openshift-user-workload-monitoring
  labels:
    k8s-app: metricbeat-user-workloads
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs: ["get", "create", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: metricbeat-kubeadm-config-user-workloads
  namespace: openshift-user-workload-monitoring
  labels:
    k8s-app: metricbeat-user-workloads
rules:
  - apiGroups: [""]
    resources:
      - configmaps
    resourceNames:
      - kubeadm-config
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metricbeat-user-workloads
subjects:
- kind: ServiceAccount
  name: metricbeat
  namespace: openshift-user-workload-monitoring
roleRef:
  kind: ClusterRole
  name: metricbeat-user-workloads
  apiGroups: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: metricbeat-user-workloads
  namespace: openshift-user-workload-monitoring
subjects:
- kind: ServiceAccount
  name: metricbeat
  namespace: openshift-user-workload-monitoring
roleRef:
  kind: Role
  name: metricbeat-user-workloads
  apiGroups: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: metricbeat-kubeadm-config-user-workloads
  namespace: openshift-user-workload-monitoring
subjects:
- kind: ServiceAccount
  name: metricbeat
  namespace: openshift-user-workload-monitoring
roleRef:
  kind: Role
  name: metricbeat-kubeadm-config-user-workloads
  apiGroups: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metricbeat-user-workloads
  labels:
    k8s-app: metricbeat-user-workloads
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - namespaces
      - events
      - pods
      - services
      - nodes/metrics
      - nodes/stats
    verbs: ["get", "list", "watch"]
  - apiGroups: ["extensions"]
    resources:
      - replicasets
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources:
      - statefulsets
      - deployments
      - replicasets
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources:
      - jobs 
    verbs: ["get", "list", "watch"]
  - apiGroups: 
    - ""
    resources:
      - nodes /stats
    verbs: 
      - get
  - nonResourceURLs:
    - "/metrics"
    verbs:
    - get
